name: contracts

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest

    # run everything in contracts directory
    defaults:
      run:
        working-directory: ./contracts

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
        # working-directory: .

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Show versions
        run: |
          forge --version
          bun --version

      - name: Build
        run: |
          forge install
          bun install
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
